document.write("<section>");
document.write("<h3>Otros datos del navegador:</h3>");
document.write("<p>Versión: ");
document.write(infoNavegador.version);
document.write("</p>");
document.write("<p>Plataforma: ");
document.write(infoNavegador.plataforma);
document.write("</p>");
document.write("<p>Vendedor: ");
document.write(infoNavegador.vendedor);
document.write("</p>");
document.write("<p>Agente: ");
document.write(infoNavegador.agente);
document.write("</p>");
document.write("<p>Java activo: ");
document.write(infoNavegador.javaActivo);
document.write("</p>");
document.write("</section>");